import { compareScenarios, sensitivityGrid, breakEvenProbability } from './engine.js';

const STORAGE_THEME='mateo-ui-theme'; const STORAGE_LANGUAGE='mateo-ui-language';
const defaults=[
  {name:'Focused launch',opportunities:120,successProbability:.24,revenuePerSuccess:950,costPerOpportunity:85,fixedCost:18000},
  {name:'Broad campaign',opportunities:260,successProbability:.15,revenuePerSuccess:760,costPerOpportunity:61,fixedCost:12500},
];
let language=localStorage.getItem(STORAGE_LANGUAGE)||(navigator.language.toLowerCase().startsWith('es')?'es':'en');
let lastResult=null;
const $=(selector)=>document.querySelector(selector); const money=new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0});
const t=(en,es)=>language==='es'?es:en;

function applyPreferences(){
  const theme=localStorage.getItem(STORAGE_THEME)||'light'; document.documentElement.dataset.theme=theme;
  document.documentElement.lang=language; document.querySelectorAll('[data-en][data-es]').forEach((el)=>{el.textContent=el.dataset[language]});
  $('#language').textContent=language==='es'?'EN':'ES'; $('#theme').textContent=theme==='dark'?'☀':'◐';
}
function scenarioTemplate(s,index){const letter=index?'B':'A';return `<article class="scenario ${letter.toLowerCase()}"><div class="scenario-head"><div><p class="eyebrow">${t('Scenario','Escenario')} ${letter}</p><h2>${t('Assumptions','Supuestos')}</h2></div><span class="scenario-badge">${letter}</span></div><div class="fields"><label class="field wide">${t('Name','Nombre')}<input data-scenario="${index}" data-field="name" value="${s.name}"></label><label class="field">${t('Opportunities','Oportunidades')}<small>${t('trials in each run','intentos por ejecución')}</small><input type="number" min="1" max="100000" data-scenario="${index}" data-field="opportunities" value="${s.opportunities}"></label><label class="field">${t('Success probability','Probabilidad de éxito')}<small>0–100%</small><input type="number" min="0" max="100" step=".1" data-scenario="${index}" data-field="successProbability" value="${s.successProbability*100}"></label><label class="field">${t('Revenue / success','Ingreso / éxito')}<small>USD</small><input type="number" min="0" data-scenario="${index}" data-field="revenuePerSuccess" value="${s.revenuePerSuccess}"></label><label class="field">${t('Cost / opportunity','Costo / oportunidad')}<small>USD</small><input type="number" min="0" data-scenario="${index}" data-field="costPerOpportunity" value="${s.costPerOpportunity}"></label><label class="field wide">${t('Fixed cost','Costo fijo')}<small>USD</small><input type="number" min="0" data-scenario="${index}" data-field="fixedCost" value="${s.fixedCost}"></label></div><p class="error" aria-live="polite"></p></article>`}
function renderEditors(values=defaults){$('#scenarioEditors').innerHTML=values.map(scenarioTemplate).join('')}
function readScenarios(){const values=[{},{}];document.querySelectorAll('[data-scenario]').forEach((input)=>{let value=input.value;if(input.type==='number')value=Number(value);if(input.dataset.field==='successProbability')value/=100;values[Number(input.dataset.scenario)][input.dataset.field]=value});return values}
function metric(label,value,detail){return `<article><span>${label}</span><strong>${value}</strong><small>${detail}</small></article>`}
function renderMetrics(result){const winner=result.winnerByMean==='a'?result.a:result.b;$('#metrics').innerHTML=[metric(t('Recommended','Recomendado'),winner.scenario.name,t('highest simulated mean','mayor media simulada')),metric(t('Expected mean','Media esperada'),money.format(winner.summary.mean),`${result.iterations||winner.iterations} ${t('runs','ejecuciones')}`),metric(t('Profit probability','Probabilidad positiva'),`${(winner.summary.probabilityOfProfit*100).toFixed(1)}%`,t('outcomes at or above zero','resultados en cero o más')),metric(t('Downside P05','Riesgo P05'),money.format(winner.summary.p05),t('fifth percentile','percentil cinco'))].join('');$('#winner').textContent=winner.scenario.name;$('#meanDifference').textContent=money.format(Math.abs(result.meanDifference));$('#winnerReason').textContent=t(`${winner.scenario.name} has the higher simulated average. Compare downside before choosing.`,`${winner.scenario.name} tiene el mayor promedio simulado. Compará el riesgo antes de elegir.`)}
function renderChart(result){const all=[...result.a.profits,...result.b.profits],min=Math.min(...all),max=Math.max(...all),bins=30,width=700,height=245,x=(value)=>30+((value-min)/(max-min||1))*width;function counts(values){const out=Array(bins).fill(0);values.forEach(v=>out[Math.min(bins-1,Math.floor(((v-min)/(max-min||1))*bins))]++);return out}const ca=counts(result.a.profits),cb=counts(result.b.profits),peak=Math.max(...ca,...cb),path=(arr,offset)=>arr.map((count,i)=>`${i?'L':'M'} ${30+(i/(bins-1))*width} ${270-(count/peak)*height+offset}`).join(' ');$('#distributionChart').innerHTML=`<defs><linearGradient id="areaA" x1="0" y1="0" x2="0" y2="1"><stop stop-color="var(--accent)" stop-opacity=".35"/><stop offset="1" stop-color="var(--accent)" stop-opacity="0"/></linearGradient></defs><line x1="${x(0)}" y1="20" x2="${x(0)}" y2="270" stroke="var(--line)" stroke-dasharray="5"/><path d="${path(ca,-4)}" fill="none" stroke="var(--accent)" stroke-width="4"/><path d="${path(cb,4)}" fill="none" stroke="var(--accent2)" stroke-width="4"/>`;$('#axisMin').textContent=money.format(min);$('#axisMax').textContent=money.format(max)}
function renderRisk(result){$('#riskComparison').innerHTML=[result.a,result.b].map((run,index)=>{const s=run.summary,be=breakEvenProbability(run.scenario);return `<div class="risk-row"><header><strong>${index?'B':'A'} · ${run.scenario.name}</strong><b>${(s.probabilityOfProfit*100).toFixed(1)}%</b></header><div class="risk-bar"><i style="width:${s.probabilityOfProfit*100}%"></i></div><dl><div><dt>P05</dt><dd>${money.format(s.p05)}</dd></div><div><dt>${t('Break-even chance','Prob. equilibrio')}</dt><dd>${be===null?'—':`${(be*100).toFixed(1)}%`}</dd></div><div><dt>P95</dt><dd>${money.format(s.p95)}</dd></div><div><dt>${t('Volatility','Volatilidad')}</dt><dd>${money.format(s.standardDeviation)}</dd></div></dl></div>`}).join('')}
function renderHeatmap(scenario){const grid=sensitivityGrid(scenario);const max=Math.max(...grid.values.flat().map(Math.abs),1);$('#heatmap').innerHTML=grid.values.flatMap((row,r)=>row.map((value,c)=>{const strength=.12+.7*Math.abs(value)/max;const color=value>=0?`rgba(8,127,91,${strength})`:`rgba(201,42,42,${strength})`;return `<div class="heat-cell" style="background:${color}" title="p ${(grid.probabilities[r]*100).toFixed(1)}% · ${money.format(grid.revenues[c])}">${money.format(value)}</div>`})).join('')}
function simulate(){document.querySelectorAll('.error').forEach(e=>e.textContent='');try{const scenarios=readScenarios(),iterations=Number($('#iterations').value),seed=Number($('#seed').value);lastResult=compareScenarios(scenarios[0],scenarios[1],{iterations,seed});lastResult.iterations=iterations;renderMetrics(lastResult);renderChart(lastResult);renderRisk(lastResult);renderHeatmap(scenarios[0])}catch(error){document.querySelector('.error').textContent=error.message}}
function exportCsv(){if(!lastResult)return;const rows=['iteration,scenario_a_profit,scenario_b_profit'];lastResult.a.profits.forEach((v,i)=>rows.push(`${i+1},${v},${lastResult.b.profits[i]}`));const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));link.download=`decision-simulation-seed-${lastResult.a.seed}.csv`;link.click();URL.revokeObjectURL(link.href)}
renderEditors();applyPreferences();simulate();
$('#simulate').addEventListener('click',simulate);$('#scenarioEditors').addEventListener('change',simulate);$('#iterations').addEventListener('change',simulate);$('#randomSeed').addEventListener('click',()=>{$('#seed').value=Math.floor(Math.random()*1e9);simulate()});$('#loadExample').addEventListener('click',()=>{renderEditors(defaults);$('#seed').value=42;simulate();location.hash='model'});$('#exportCsv').addEventListener('click',exportCsv);
$('#theme').addEventListener('click',()=>{localStorage.setItem(STORAGE_THEME,document.documentElement.dataset.theme==='dark'?'light':'dark');applyPreferences()});$('#language').addEventListener('click',()=>{language=language==='es'?'en':'es';localStorage.setItem(STORAGE_LANGUAGE,language);applyPreferences();const values=readScenarios();renderEditors(values);simulate()});
addEventListener('pointermove',(event)=>{document.documentElement.style.setProperty('--cursor-x',`${event.clientX}px`);document.documentElement.style.setProperty('--cursor-y',`${event.clientY}px`)});const observer=new IntersectionObserver((entries)=>entries.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{threshold:.08});document.querySelectorAll('.reveal').forEach((element)=>observer.observe(element));
